CREATE TABLE `team_schedule` (
  `Status` varchar(3),
  `#` int(11),
  `Type` varchar(7),
  `Day` varchar(3),
  `Date` varchar(10),
  `Time ET` varchar(8),
  `Local` varchar(8),
  `Puck ET` varchar(3),
  `Format` varchar(7),
  `Venue` varchar(24),
  `Home Split Squad` varchar(1),
  `Away Split Squad` varchar(1),
  `Visiting` varchar(3),
  `Home` varchar(3),
  `United States` varchar(1),
  `Canada` varchar(1),
  `Away TV` varchar(1),
  `Home TV` varchar(1)
);